---
abstract: "SYP's cozy environment"
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-SYP
requires:
  perl: 5.006
resources:
  bugtracker: https://github.com/creaktive/Bundle-SYP/issues
  homepage: https://github.com/creaktive/Bundle-SYP
  repository: git://github.com/creaktive/Bundle-SYP.git
version: 0.2
